// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpvsormfdkekrhnohuxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwdnNvcm1mZGtla3Jobm9odXh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NDM1NzcsImV4cCI6MjA1OTMxOTU3N30.tNZAI7FuTkbxFxypZsw9MK8byf3EWuIc-1karcwJ8KM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);